remote_theme: fongandrew/hydeout

# Site Settings
locale                   : "en-US"
title                    : "pyLLE"
title_separator          : "-"
name                     : &name "Gregory Moille" # &name is a YAML anchor which can be *referenced later
description              : &description "A Fast and User-Friendly Lugiato Lefever Equation Solver"
url                      : https://gregmoille.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/pyLLE" # the subpath of your site, e.g. "/blog"
repository               : "gregmoille/pyLLE"

sidebar_home_link:  true


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
author:
  name:           'Gregory Moille'
  url:            https://twitter.com/greg_moille

markdown:         kramdown
highlighter:      rouge


hydeout:
  repo: https://github.com/gregmoille/pyLLE